# Generated by Django 5.0.2 on 2024-02-18 01:48

import django.db.models.deletion
import phonenumber_field.modelfields
import portfolios.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("course", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bnumber", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("major", models.CharField(max_length=10)),
                (
                    "admission_year",
                    models.IntegerField(
                        choices=portfolios.models.year_choices,
                        default=portfolios.models.current_year,
                        verbose_name="year",
                    ),
                ),
                ("current_gpa", models.FloatField(null=True)),
                (
                    "mobile_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("addrress", models.CharField(max_length=200, null=True)),
                ("linkedin_url", models.URLField(null=True)),
                ("github_url", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_year",
                    models.IntegerField(
                        choices=portfolios.models.year_choices,
                        default=portfolios.models.current_year,
                        verbose_name="year",
                    ),
                ),
                (
                    "end_year",
                    models.IntegerField(
                        choices=portfolios.models.year_choices,
                        default=portfolios.models.current_year,
                        verbose_name="year",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolios.student",
                    ),
                ),
            ],
        ),
    ]
