# Generated by Django 5.0.2 on 2024-02-20 18:44

import django.db.models.deletion
import phonenumber_field.modelfields
import portfolios.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ExpertiseArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(default="description", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "bnumber",
                    portfolios.models.BNumberField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("graduated", models.BooleanField(default=False)),
                ("major", models.CharField(max_length=10)),
                (
                    "admission_year",
                    models.IntegerField(
                        choices=portfolios.models.year_choices,
                        default=portfolios.models.current_year,
                        verbose_name="year",
                    ),
                ),
                ("current_gpa", models.FloatField(null=True)),
                (
                    "mobile_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("address", models.CharField(max_length=200, null=True)),
                ("linkedin_url", models.URLField(null=True)),
                ("github_url", models.URLField(null=True)),
                ("image_url", models.CharField(max_length=100, null=True)),
                (
                    "current_role",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_students",
                        to="portfolios.role",
                    ),
                ),
                (
                    "expertise_areas",
                    models.ManyToManyField(to="portfolios.expertisearea"),
                ),
                (
                    "preferred_roles",
                    models.ManyToManyField(
                        related_name="preferred_students", to="portfolios.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("project_url", models.URLField(null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="portfolios.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="portfolios.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ongoing", models.BooleanField(default=False)),
                ("degree_name", models.CharField(max_length=200)),
                (
                    "start_year",
                    models.IntegerField(
                        choices=portfolios.models.year_choices,
                        default=portfolios.models.current_year,
                        verbose_name="year",
                    ),
                ),
                (
                    "end_year",
                    models.IntegerField(
                        choices=portfolios.models.year_choices,
                        default=portfolios.models.current_year,
                        null=True,
                        verbose_name="year",
                    ),
                ),
                ("university", models.CharField(max_length=200)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolios.country",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="portfolios.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_year"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "start_year",
                    models.IntegerField(
                        choices=portfolios.models.year_choices,
                        default=portfolios.models.current_year,
                        verbose_name="year",
                    ),
                ),
                (
                    "end_year",
                    models.IntegerField(
                        choices=portfolios.models.year_choices,
                        default=portfolios.models.current_year,
                        null=True,
                        verbose_name="year",
                    ),
                ),
                ("ongoing", models.BooleanField(default=False)),
                (
                    "country",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolios.country",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolios.role",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="portfolios.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_year"],
            },
        ),
    ]
