# Generated by Django 5.0.2 on 2024-02-18 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="addrress",
            new_name="address",
        ),
    ]
